export const LOGIN_SUCCESS= "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const USER_LOADING='USER_LOADING'
export const REGISTER_SUCCESS='USER_SUCCESS'
export const AUTH='AUTH'
export const USER_LOADED='USER_LOADED'